# API

## Login
POST http://localhost:9091/api/auth/local
Content-Type: application/json

{
    "identifier": "wachi3079@gmail.com",
    "password": "Wach1@3079"
}

###

## Forgot (ลืมรหัสผ่าน)
POST http://localhost:9091/api/auth/forgot-password
Content-Type: application/json

{
    "email": "wachi3079@gmail.com"
}

###

## Profile (ดูข้อมูลส่วนตัว)
GET http://localhost:9091/api/users/me
Authorization: Bearer <ใส่_TOKEN_ที่ได้จากตอน_LOGIN_หรือ_REGISTER>

###

## Register / Signup (สมัครสมาชิก)
POST http://localhost:9091/api/auth/local/register
Content-Type: application/json

{
    "username": "wachi",
    "email": "wachi3079@gmail.com",
    "password": "Wach1@3079"
}